SAMPLE_SESSION = {
    "title": "Wohin fahren wir im Juli?",
    "participants": ["Mia", "Jonas", "Lea"],
    "alternatives": ["Lissabon", "Kopenhagen", "Mallorca"],
    "criteria": [
        {"name": "Budget", "weight": 30},
        {"name": "Wetter", "weight": 25},
        {"name": "Aktivitäten", "weight": 25},
        {"name": "Reisezeit", "weight": 20},
    ],
    "ratings": [
        {"participant": "Mia", "alternative": "Lissabon", "criterion": "Budget", "value": 4},
        {"participant": "Mia", "alternative": "Lissabon", "criterion": "Wetter", "value": 5},
        {"participant": "Mia", "alternative": "Lissabon", "criterion": "Aktivitäten", "value": 5},
        {"participant": "Mia", "alternative": "Lissabon", "criterion": "Reisezeit", "value": 4},
        {"participant": "Mia", "alternative": "Kopenhagen", "criterion": "Budget", "value": 3},
        {"participant": "Mia", "alternative": "Kopenhagen", "criterion": "Wetter", "value": 3},
        {"participant": "Mia", "alternative": "Kopenhagen", "criterion": "Aktivitäten", "value": 4},
        {"participant": "Mia", "alternative": "Kopenhagen", "criterion": "Reisezeit", "value": 4},
        {"participant": "Mia", "alternative": "Mallorca", "criterion": "Budget", "value": 3},
        {"participant": "Mia", "alternative": "Mallorca", "criterion": "Wetter", "value": 4},
        {"participant": "Mia", "alternative": "Mallorca", "criterion": "Aktivitäten", "value": 3},
        {"participant": "Mia", "alternative": "Mallorca", "criterion": "Reisezeit", "value": 5},
        {"participant": "Jonas", "alternative": "Lissabon", "criterion": "Budget", "value": 4},
        {"participant": "Jonas", "alternative": "Lissabon", "criterion": "Wetter", "value": 4},
        {"participant": "Jonas", "alternative": "Lissabon", "criterion": "Aktivitäten", "value": 4},
        {"participant": "Jonas", "alternative": "Lissabon", "criterion": "Reisezeit", "value": 4},
        {"participant": "Jonas", "alternative": "Kopenhagen", "criterion": "Budget", "value": 3},
        {"participant": "Jonas", "alternative": "Kopenhagen", "criterion": "Wetter", "value": 4},
        {"participant": "Jonas", "alternative": "Kopenhagen", "criterion": "Aktivitäten", "value": 4},
        {"participant": "Jonas", "alternative": "Kopenhagen", "criterion": "Reisezeit", "value": 3},
        {"participant": "Jonas", "alternative": "Mallorca", "criterion": "Budget", "value": 4},
        {"participant": "Jonas", "alternative": "Mallorca", "criterion": "Wetter", "value": 5},
        {"participant": "Jonas", "alternative": "Mallorca", "criterion": "Aktivitäten", "value": 4},
        {"participant": "Jonas", "alternative": "Mallorca", "criterion": "Reisezeit", "value": 4},
        {"participant": "Lea", "alternative": "Lissabon", "criterion": "Budget", "value": 5},
        {"participant": "Lea", "alternative": "Lissabon", "criterion": "Wetter", "value": 4},
        {"participant": "Lea", "alternative": "Lissabon", "criterion": "Aktivitäten", "value": 4},
        {"participant": "Lea", "alternative": "Lissabon", "criterion": "Reisezeit", "value": 4},
        {"participant": "Lea", "alternative": "Kopenhagen", "criterion": "Budget", "value": 3},
        {"participant": "Lea", "alternative": "Kopenhagen", "criterion": "Wetter", "value": 3},
        {"participant": "Lea", "alternative": "Kopenhagen", "criterion": "Aktivitäten", "value": 5},
        {"participant": "Lea", "alternative": "Kopenhagen", "criterion": "Reisezeit", "value": 3},
        {"participant": "Lea", "alternative": "Mallorca", "criterion": "Budget", "value": 4},
        {"participant": "Lea", "alternative": "Mallorca", "criterion": "Wetter", "value": 4},
        {"participant": "Lea", "alternative": "Mallorca", "criterion": "Aktivitäten", "value": 4},
        {"participant": "Lea", "alternative": "Mallorca", "criterion": "Reisezeit", "value": 5},
    ],
}
